### ISSUE TITLE
Python script attribute error when opening on Dodi 17.6

### ISSUE THREAD

**Issue by nchauley** [jsergio123/plugin.video.adultswim#2]
Addon was working until about 2 weeks ago. Error log attached.
Thx for all your plugins and assistance. Much appreciated!

Nvidia Shield TV
Android 8.0.0
Dodi 17.6
[ErrorLog.txt](https://github.com/jsergio123/plugin.video.adultswim/files/2921316/ErrorLog.txt)

**Comment by imrelaxed** [comment]
same problem on fire tv

**Comment by o-leary** [comment]
Also on Vero4k. Both this plugin and another adult swim plugin stopped at the same time with the same error in the log, so presumably the adult swim api has changed. I haven’t found time to look further. One of the two plugins allowed the archived live streams like SMB which is the best show on the internet, so if it as the other one I’ll port any fix into that too.

**Comment by imrelaxed** [comment]
The plugin does not interact with an API, it rips the episodes straight from the adult swim video web site. As far as I can tell the issue is scraping data for the show menu inside the plugin, data that includes the stream url link, the plugin runs a regex search re.search('''__AS_INITIAL_STATE__\s*=\s*({.+?})</script>''', html).groups()[0] that fails because presumably adult swim changed the code on the site and the regex is no longer valid. If I knew the specific section of code the regex used to rip before adultswim made code changes then I could update it myself, alas I do not. Going to go see if I can load the old version of adultswim via archive.org

**Comment by imrelaxed** [comment]
Ok found the old code for AS, making updates to the regex

**Comment by imrelaxed** [comment]
No luck with fixing the regex on my own, my python skills are too weak. Here is the updated code from adult swim videos web site if someone else wants to have a go: 
`<script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"description":"Watch free full episodes, online videos, clips and web exclusives at AdultSwim.com.","featuredStream":{"title":"[as] Live Stream","url":"/streams","video":"r0xw2u30R3GchW27yVqlug"},"shows":[{"poster":"https://i.cdn.turner.com/adultswim/big/img/2018/11/09/12ozMouse_PosterImage_1.jpg","slug":"12-oz-mouse","title":"12 oz. Mouse","url":"/videos/12-oz-mouse"},{"poster":"https://i.cdn.turner.com/adultswim/big/img/2019/02/07/CelebPoker_index208x277.jpg","slug":"adult-swim-celebrity-poker-tournament-royale","title":"Adult Swim Celebrity Poker Tournament Royale","url":"/videos/adult-swim-celebrity-poker-tournament-royale"},{"poster":"https://i.cdn.turner.com/adultswim/big/img/2019/01/16/AmericanDad_Posterimage.jpg","slug":"american-dad","title":"American Dad","url":"/videos/american-dad"},{"poster":"https://i.cdn.turner.com/adultswim/big/img/2018/11/09/01_ApolloGauntlet_PosterImage.png.jpg","slug":"apollo-gauntlet","title":"Apollo Gauntlet","url":"/videos/apollo-gauntlet"},{"poster":"https://i.cdn.turner.com/adultswim/big/img/2018/11/15/AquaTeenHungerForce_PosterImage.png","slug":"aqua-teen-hunger-force","title":"Aqua Teen Hunger Force","url":"/videos/aqua-teen-hunger-force"},{"poster":"https://i.cdn.turner.com/adultswim/big/img/2018/06/27/AsSeenOn_PosterImage.jpg","slug":"as-seen-on-adult-swim","title":"As Seen On Adult Swim","url":"/videos/as-seen-on-adult-swim"},`

My failed attempt at a fix:
`data = re.search('''<script id=\"__NEXT_DATA__\" type=\"application/json\">({.+?})</script>''', html).groups()[0]`
`shows = data.get("props").get("shows")`

New error is a NoneType at line 36 total = len(shows)

**Comment by o-leary** [comment]
Could be my eyes, it’s late, but doesn’t the source look like data.get(“props”).get(“pageProps”).get(“shows”) would work. Looks like shows is nested in pageProps. Apologies if I’m off base I’ll take a proper look tomorrow if you haven’t cracked it.

**Comment by jsergio123** [comment]
Sorry guys. I'll take a look later at the changes needing to be made..

**Comment by imrelaxed** [comment]
> Could be my eyes, it’s late, but doesn’t the source look like data.get(“props”).get(“pageProps”).get(“shows”) would work. Looks like shows is nested in pageProps. Apologies if I’m off base I’ll take a proper look tomorrow if you haven’t cracked it. Sent from my mobile.
> […](#)
> On 7/03/2019, at 9:02 PM, imrelaxed ***@***.***> wrote: No luck with fixing the regex on my own, my python skills are too weak. Here is the updated code from adult swim videos web site if someone else wants to have a go: <script id="__NEXT_DATA__" type="application/json">{"props":{"pageProps":{"description":"Watch free full episodes, online videos, clips and web exclusives at AdultSwim.com.","featuredStream":{"title":"[as] Live Stream","url":"/streams","video":"r0xw2u30R3GchW27yVqlug"},"shows":[{"poster":"[https://i.cdn.turner.com/adultswim/big/img/2018/11/09/12ozMouse_PosterImage_1.jpg","slug":"12-oz-mouse","title":"12](https://i.cdn.turner.com/adultswim/big/img/2018/11/09/12ozMouse_PosterImage_1.jpg%22,%22slug%22:%2212-oz-mouse%22,%22title%22:%2212) oz. Mouse","url":"/videos/12-oz-mouse"},{"poster":"[https://i.cdn.turner.com/adultswim/big/img/2019/02/07/CelebPoker_index208x277.jpg","slug":"adult-swim-celebrity-poker-tournament-royale","title":"Adult](https://i.cdn.turner.com/adultswim/big/img/2019/02/07/CelebPoker_index208x277.jpg%22,%22slug%22:%22adult-swim-celebrity-poker-tournament-royale%22,%22title%22:%22Adult) Swim Celebrity Poker Tournament Royale","url":"/videos/adult-swim-celebrity-poker-tournament-royale"},{"poster":"[https://i.cdn.turner.com/adultswim/big/img/2019/01/16/AmericanDad_Posterimage.jpg","slug":"american-dad","title":"American](https://i.cdn.turner.com/adultswim/big/img/2019/01/16/AmericanDad_Posterimage.jpg%22,%22slug%22:%22american-dad%22,%22title%22:%22American) Dad","url":"/videos/american-dad"},{"poster":"[https://i.cdn.turner.com/adultswim/big/img/2018/11/09/01_ApolloGauntlet_PosterImage.png.jpg","slug":"apollo-gauntlet","title":"Apollo](https://i.cdn.turner.com/adultswim/big/img/2018/11/09/01_ApolloGauntlet_PosterImage.png.jpg%22,%22slug%22:%22apollo-gauntlet%22,%22title%22:%22Apollo) Gauntlet","url":"/videos/apollo-gauntlet"},{"poster":"[https://i.cdn.turner.com/adultswim/big/img/2018/11/15/AquaTeenHungerForce_PosterImage.png","slug":"aqua-teen-hunger-force","title":"Aqua](https://i.cdn.turner.com/adultswim/big/img/2018/11/15/AquaTeenHungerForce_PosterImage.png%22,%22slug%22:%22aqua-teen-hunger-force%22,%22title%22:%22Aqua) Teen Hunger Force","url":"/videos/aqua-teen-hunger-force"},{"poster":"[https://i.cdn.turner.com/adultswim/big/img/2018/06/27/AsSeenOn_PosterImage.jpg","slug":"as-seen-on-adult-swim","title":"As](https://i.cdn.turner.com/adultswim/big/img/2018/06/27/AsSeenOn_PosterImage.jpg%22,%22slug%22:%22as-seen-on-adult-swim%22,%22title%22:%22As) Seen On Adult Swim","url":"/videos/as-seen-on-adult-swim"}, My failed attempt at a fix: data = re.search('''<script id=\"__NEXT_DATA__\" type=\"application/json\">({.+?})</script>''', html).groups()[0] shows = data.get("props").get("shows") New error is a NoneType at line 36 total = len(shows) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.

You are right, I should have visualized the json to avoid this mistake. I am getting an incorrect syntax error with the updated code though, which is odd since triple nesting of get should be fine in python afaik, going to try a different approach.

**Comment by imrelaxed** [comment]
Going to let jsergio handle this, since he's here now. Thank you jsergio. =)

**Comment by jsergio123** [comment]
Fixed. See here https://github.com/jsergio123/plugin.video.adultswim/commit/8955c3f8bd84d7d66dd3acf32f34415b71e43af3

Update 2.0.1 available in my repo. Sorry for not fixing it sooner.

**Comment by nchauley** [comment]
Tested and works like a charm! Many thanks for your quick fix...

**Comment by o-leary** [comment]
Thanks! Works perfectly - well now that I removed SMB from the blacklist. Not sure why it was there as it plays fine.
